name: Deploy Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Build and Deploy
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm

      - name: Set version
        run: |
          version=$(date +'%Y%m%d.%H%M%S')
          printf '{"version": "%s" }' "$version" > public/version.json

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}